### ISSUE TITLE
No models in MMSA_regression_checkpoints?

### ISSUE THREAD

**Issue by lucaro** [njumagus/MMSF#2]
When trying to run `python feat_extract/MMSA_senti_feat.py` I get an assertion error because `self_mm-mosi_lvu.pth` is not present in `MMSF/feat_extract/MMSA_regression_checkpoints`. The folder is empty. Where are these models supposed to come from?

**Comment by yfraquelle** [comment]
@lucaro You can find the file in feat_extract.zip from the download link at Baidu Disk.

**Comment by lucaro** [comment]
Hey, I tried downloading things from there, but I always run into problems. I also have not found a way to set the UI to English, so I can't really tell what is going on.
![image](https://github.com/njumagus/MMSF/assets/246519/f98e481e-aade-4098-a0d8-ece4683f3296)
![image](https://github.com/njumagus/MMSF/assets/246519/b3d937c4-3292-4bf2-83b3-6b759f5739a5)

**Comment by yfraquelle** [comment]
Given the issues you're facing, I'll try uploading the files to an alternative disk. I'll make updates to the README file and respond to you once the files are uploaded.

**Comment by yfraquelle** [comment]
I have uploaded the files to OneDrive (https://1drv.ms/f/s!AqIJSYD5gt-YlC-D4ONCfKefbNKI?e=aC8Xhw).  Feel free to let me know if you encounter any issues while downloading the files.
